# values-aks.yaml
# Entorno de Producción en AKS (Azure)

# Configuración Global
global:
  registry: ghcr.io

# API Gateway
api-gateway:
  replicaCount: 2
  image:
    repository: ghcr.io/andrescalvo98/sa-api-gateway
    tag: "d66125fe88f7cedfaa8ad25fe2a2ffe9b598dafa"
    pullPolicy: Always

# Auth Service
auth-service:
  replicaCount: 2
  image:
    repository: ghcr.io/andrescalvo98/sa-auth-service
    tag: "d66125fe88f7cedfaa8ad25fe2a2ffe9b598dafa"
    pullPolicy: Always

# Transaction Service
transaction-service:
  replicaCount: 2
  image:
    repository: ghcr.io/andrescalvo98/sa-transaction-service
    tag: "d66125fe88f7cedfaa8ad25fe2a2ffe9b598dafa"
    tag: "5569393dcd5e4eebdf1e1bef78bc099c7b01fcb4"
    pullPolicy: Always

# Approval Service
approval-service:
  replicaCount: 2
  image:
    repository: ghcr.io/andrescalvo98/sa-approval-service
    tag: "5569393dcd5e4eebdf1e1bef78bc099c7b01fcb4"
    pullPolicy: Always

# Notification Service
notification-service:
  replicaCount: 2
  image:
    repository: ghcr.io/andrescalvo98/sa-notification-service
    tag: "5569393dcd5e4eebdf1e1bef78bc099c7b01fcb4"
    pullPolicy: Always

# Configuración de los CronJobs
cronjobs:
  insertDb:
    image:
      repository: ghcr.io/andrescalvo98/sa-cronjob-insert-db
      tag: "d66125fe88f7cedfaa8ad25fe2a2ffe9b598dafa"
      pullPolicy: Always
  summaryBroker:
    image:
      repository: ghcr.io/andrescalvo98/sa-cronjob-summary-broker
      tag: "d66125fe88f7cedfaa8ad25fe2a2ffe9b598dafa"
      pullPolicy: Always

# Persistencia de Postgres (Usará los discos Managed-CSI por defecto de AKS)
postgresql:
  image:
    tag: latest
  primary:
    persistence:
      size: 1Gi
      # No especificamos storageClass para que Azure asigne su default

rabbitmq:
  auth:
    username: "user"
    existingPasswordSecret: "sa-platform-secrets"
