# Valores base
global:
  namespace: sa-p5

# API Gateway (NGINX Proxy)
api-gateway:
  replicaCount: 1
  image:
    repository: mi-repo/api-gateway
  service:
    port: 80
  probes:
    enabled: false # Nginx basico no tiene endpoint especial para probe
  autoscaling:
    minReplicas: 2
    maxReplicas: 5

auth-service:
  fullnameOverride: "sa-platform-auth-service"
  image:
    repository: mi-repo/auth-service
  service:
    port: 4000
  probes:
    enabled: false
  env:
    NODE_ENV: production

transaction-service:
  fullnameOverride: "sa-platform-transaction-service"
  image:
    repository: mi-repo/transaction-service
  service:
    port: 4001
  probes:
    enabled: false
  env: {}

approval-service:
  fullnameOverride: "sa-platform-approval-service"
  image:
    repository: mi-repo/approval-service
  service:
    port: 4002
  probes:
    enabled: false
  env: {}

notification-service:
  fullnameOverride: "sa-platform-notification-service"
  image:
    repository: mi-repo/notification-service
  service:
    port: 4003
  probes:
    enabled: false
  env: {}


postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "16.6.0"
  auth:
    username: ""
    existingSecret: "sa-platform-secrets"
    database: "transacciones"
  primary:
    podLabels:
      app: sa-platform-postgresql
    persistence:
      enabled: true
      size: 1Gi

cronjobs:
  insertDb:
    image:
      repository: ghcr.io/andrescalvo98/sa-cronjob-insert-db
      tag: latest
      pullPolicy: Always
  summaryBroker:
    image:
      repository: ghcr.io/andrescalvo98/sa-cronjob-summary-broker
      tag: latest
      pullPolicy: Always

rabbitmq:
  podLabels:
    app: sa-platform-rabbitmq
  auth:
    username: "AndresCalvo"
    existingPasswordSecret: "sa-platform-secrets"
