apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-insert-db
  labels:
    app.kubernetes.io/name: cronjob-insert-db
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: sa-platform-cronjobs
          restartPolicy: OnFailure
          containers:
          - name: cronjob1
            image: "{{ .Values.cronjobs.insertDb.image.repository }}:{{ .Values.cronjobs.insertDb.image.tag }}"
            imagePullPolicy: {{ .Values.cronjobs.insertDb.image.pullPolicy }}
            envFrom:
            - secretRef:
                name: sa-platform-secrets
            env:
            - name: CARNE
              value: "201712620"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-summary-broker
  labels:
    app.kubernetes.io/name: cronjob-summary-broker
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: sa-platform-cronjobs
          restartPolicy: OnFailure
          containers:
          - name: cronjob2
            image: "{{ .Values.cronjobs.summaryBroker.image.repository }}:{{ .Values.cronjobs.summaryBroker.image.tag }}"
            imagePullPolicy: {{ .Values.cronjobs.summaryBroker.image.pullPolicy }}
            envFrom:
            - secretRef:
                name: sa-platform-secrets
