apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-secrets
  namespace: produccion
spec:
  encryptedData:
    password: AgBy3i4OJSWK+PiMtW...
    postgres-password: AgBy3i4OJSWK+PiMtW...
  template:
    metadata:
      name: sa-platform-secrets
      namespace: produccion
