apiVersion: v1
kind: Secret
metadata:
  name: sa-platform-secrets
type: Opaque
data:
  DB_HOST: {{ printf "%s-postgresql" .Release.Name | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.auth.username | default "postgres" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | default "secretpassword" | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | default "transacciones" | b64enc | quote }}
  RABBITMQ_URL: {{ printf "amqp://%s:%s@%s-rabbitmq:5672" (.Values.rabbitmq.auth.username | default "user") (.Values.rabbitmq.auth.password | default "password") .Release.Name | b64enc | quote }}
