apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
